#!/usr/bin/env python3
"""
YouTube故事性AI视频 → B站 自动搬运脚本
每天10:00和20:00自动运行

流程: YouTube英文搜索 → 下载 → B站上传 → 记录历史
"""
from __future__ import annotations

import os
os.environ["PATH"] = "/Users/kaikai/bin:" + os.environ.get("PATH", "")

import asyncio
import fcntl
import json
import random
import shutil
import subprocess
import sys
import time
import urllib.parse
import re
from datetime import datetime, timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

# 添加config路径用于LLM
sys.path.insert(0, "/Users/kaikai/scripts")
sys.path.insert(1, "/Users/kaikai/scripts/config")
sys.path.insert(2, "/Users/kaikai/scripts/llm_utils")

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# ═══════════════════════════════════════════════════════
# 配置
# ═══════════════════════════════════════════════════════
SEARCH_KEYWORDS = [
    "this week trending short film",
    "viral story short video",
    "trending today story",
    "new viral video",
    "must watch story short",
    "best new short film",
    "trending viral moments",
    "recent popular story",
]
RECENT_DAYS = 3
MAX_DOWNLOADS_PER_RUN = 2
TOP_CANDIDATES = 30          # 扩大候选池
SEARCH_COUNT_PER_KEYWORD = 20  # 每个关键词搜索页数（原来10）
SEARCH_RETRY = 3              # 搜索失败重试次数
SEARCH_TIMEOUT = 120          # 搜索超时秒数（原来60）
SEARCH_RETRY_DELAY = 5        # 重试间隔秒数
NETWORK_TEST_URL = "https://www.youtube.com"
NETWORK_TEST_TIMEOUT = 10
MAX_VIDEO_DURATION = 300  # 最大时长300秒（5分钟），跳过过长的视频

WORK_DIR = Path(__file__).parent / "downloads"
HISTORY_FILE = Path(__file__).parent / "history.json"
UPLOAD_HISTORY_FILE = Path(__file__).parent / "upload_history.json"
LOCK_FILE = Path("/tmp/tiktok_story_pipeline.lock")
LOG_FILE = Path(__file__).parent / "run.log"

BILI_COOKIE_FILE = Path(__file__).parent / "那那天下雨了_cookies.txt"
TIKTOK_COOKIE_FILE = Path(__file__).parent / "ticktoks_cookies.txt"
DOUYIN_COOKIE_FILE = Path(__file__).parent / "风走了叶落_cookies.txt"
DOUYIN_UPLOAD_SCRIPT = Path("/Users/kaikai/ai_video_upload/douyin_upload.py")

WEIGHT_LIKE = 1
WEIGHT_REPOST = 3
WEIGHT_COIN = 2

# ═══════════════════════════════════════════════════════
# 工具函数
# ═══════════════════════════════════════════════════════
def log(msg: str) -> None:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line)
    try:
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(line + "\n")
    except Exception:
        pass


def atomic_write(path: Path, data: str) -> None:
    tmp = path.with_suffix(".tmp")
    tmp.write_text(data, encoding="utf-8")
    tmp.replace(path)


def acquire_lock() -> bool:
    try:
        lfd = open(LOCK_FILE, "w")
        fcntl.flock(lfd.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        lfd.write(str(os.getpid()))
        lfd.flush()
        return True
    except (BlockingIOError, OSError):
        return False


def load_history() -> dict:
    if HISTORY_FILE.exists():
        try:
            return json.loads(HISTORY_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def save_history(h: dict) -> None:
    atomic_write(HISTORY_FILE, json.dumps(h, ensure_ascii=False, indent=2))


def load_upload_history() -> dict:
    try:
        return json.loads(UPLOAD_HISTORY_FILE.read_text(encoding="utf-8"))
    except:
        return {}


def save_upload_history(h: dict) -> None:
    atomic_write(UPLOAD_HISTORY_FILE, json.dumps(h, ensure_ascii=False, indent=2))


def load_cookies(path: Path) -> dict:
    try:
        text = path.read_text(encoding="utf-8").strip()
        if text.startswith('{') or text.startswith('['):
            return json.loads(text)
        cookies = {}
        for line in text.split('\n'):
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) >= 7:
                cookies[parts[5]] = parts[6]
        return cookies
    except Exception as e:
        log(f"加载Cookie失败 {path}: {e}")
        return {}


def get_netscape_cookie_file(cookies: dict, name: str = "tiktok") -> Path:
    lines = ["# Netscape HTTP Cookie File", f"# Generated by {name}"]
    for n, v in cookies.items():
        domain = ".tiktok.com" if name == "tiktok" else ".bilibili.com"
        flag = "TRUE"
        path = "/"
        secure = "TRUE"
        expires = "9999999999"
        lines.append(f"{domain}\tTRUE\t{path}\t{secure}\t{expires}\t{n}\t{v}")
    tmp = Path(f"/tmp/{name}_cookies.txt")
    tmp.write_text("\n".join(lines), encoding="utf-8")
    return tmp


# ═══════════════════════════════════════════════════════
# 网络 Session
# ═══════════════════════════════════════════════════════
_session = requests.Session()
_session.mount(
    "https://",
    HTTPAdapter(max_retries=Retry(total=3, backoff_factor=1.5, status_forcelist={429, 500, 502, 503, 504}))
)
_session.mount(
    "http://",
    HTTPAdapter(max_retries=Retry(total=3, backoff_factor=1.5, status_forcelist={429, 500, 502, 503, 504}))
)


# ═══════════════════════════════════════════════════════
# TikTok 搜索
# ═══════════════════════════════════════════════════════
def search_youtube(keyword: str, count: int = None) -> list[dict]:
    """用yt-dlp ytsearch搜索YouTube视频，支持重试和超时控制"""
    if count is None:
        count = SEARCH_COUNT_PER_KEYWORD
    results = []
    for attempt in range(SEARCH_RETRY):
        try:
            search_query = f"ytsearch{count}:{keyword}"
            cmd = [
                YTDLP_PY, "-m", "yt_dlp",
                "--flat-playlist",
                "--print", "%(id)s|%(duration)s|%(title)s",
                "--no-warnings",
                search_query
            ]
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=SEARCH_TIMEOUT)
            if result.returncode == 0:
                for line in result.stdout.strip().split("\n"):
                    parts = line.split("|", 2)
                    if len(parts) >= 3:
                        vid, dur, title = parts[0].strip(), parts[1].strip(), parts[2].strip()
                        if re.match(r"^[a-zA-Z0-9_-]{10,15}$", vid):
                            try:
                                duration = int(float(dur)) if dur else 0
                            except (ValueError, TypeError):
                                duration = 0
                            results.append({
                                "id": vid,
                                "title": title or f"YouTube {vid}",
                                "keyword": keyword,
                                "duration": duration,
                            })
                log(f"  [搜索] ytsearch '{keyword}' 找到 {len(results)} 个")
                return results
            else:
                err = result.stderr[-300:]
                if attempt < SEARCH_RETRY - 1:
                    log(f"  [搜索] ytsearch '{keyword}' 失败(尝试{attempt+1}/{SEARCH_RETRY}): {err[-100:]}")
                    time.sleep(SEARCH_RETRY_DELAY)
                else:
                    log(f"  [搜索] ytsearch 失败: {err[-200:]}")
        except subprocess.TimeoutExpired:
            if attempt < SEARCH_RETRY - 1:
                log(f"  [搜索] ytsearch '{keyword}' 超时{SEARCH_TIMEOUT}s(尝试{attempt+1}/{SEARCH_RETRY})，重试...")
                time.sleep(SEARCH_RETRY_DELAY)
            else:
                log(f"  [搜索] ytsearch '{keyword}' 超时{SEARCH_TIMEOUT}s * {SEARCH_RETRY}次，退出")
        except Exception as e:
            if attempt < SEARCH_RETRY - 1:
                log(f"  [搜索] ytsearch '{keyword}' 异常(尝试{attempt+1}/{SEARCH_RETRY}): {e}")
                time.sleep(SEARCH_RETRY_DELAY)
            else:
                log(f"  [搜索] ytsearch '{keyword}' 异常: {e}")
    return results


def get_youtube_video_info(video_id: str) -> dict:
    """通过yt-dlp获取YouTube视频详情"""
    try:
        cmd = [
            YTDLP_PY, "-m", "yt_dlp",
            "--cookies-from-browser", "chrome",
            "--extractor-args", "youtube:player_client=web_safari",
            "--no-playlist",
            "--print", "%(view_count)s|%(like_count)s|%(comment_count)s|%(duration)s|%(title)s",
            "--no-warnings",
            f"https://www.youtube.com/watch?v={video_id}"
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if result.returncode == 0:
            parts = result.stdout.strip().split("|", 4)
            if len(parts) >= 5:
                try:
                    view = int(parts[0]) if parts[0] and parts[0] != 'None' else 0
                    like = int(parts[1]) if parts[1] and parts[1] != 'None' else 0
                    comment = int(parts[2]) if parts[2] and parts[2] != 'None' else 0
                    duration = int(parts[3]) if parts[3] and parts[3] != 'None' else 0
                    title = parts[4]
                except (ValueError, IndexError):
                    view = like = comment = duration = 0
                    title = f"YouTube {video_id}"

                return {
                    "id": video_id,
                    "title": title,
                    "view": view,
                    "like": like,
                    "comment": comment,
                    "duration": duration,
                }
    except Exception as e:
        log(f"  [YouTube详情] {video_id}: {e}")
    return {}


# 使用 hermes venv 的 python3.11（避免系统 python3.9 deprecation 警告）
YTDLP_PY = "/Users/kaikai/.hermes/hermes-agent/venv/bin/python3"

def _check_and_fix_audio(video_path: Path) -> bool:
    """检查视频是否有音频轨道，没有则尝试用ffmpeg合并"""
    result = subprocess.run(
        ["ffprobe", "-v", "quiet", "-print_format", "json",
         "-show_streams", str(video_path)],
        capture_output=True, text=True
    )
    if result.returncode == 0 and '"codec_type":"audio"' in result.stdout:
        return True
    log(f"  [音频] 检测到无音频，尝试修复: {video_path.name}")
    # 重新用yt-dlp下载音频+视频合并
    audio_tmp = video_path.with_suffix(".audio.tmp.mp4")
    video_tmp = video_path.with_suffix(".video.tmp.mp4")
    shutil.copy(video_path, video_tmp)
    cmd = [
        YTDLP_PY, "-m", "yt_dlp",
        "--cookies-from-browser", "chrome",
        "--extractor-args", "youtube:player_client=web_safari",
        "--no-playlist",
        "-f", "bestaudio[ext=m4a]/best",
        "--no-warnings",
        "-o", str(audio_tmp),
        f"https://www.youtube.com/watch?v={video_path.stem}"
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if r.returncode == 0 and audio_tmp.exists():
        # 用ffmpeg合并
        merge_cmd = [
            "ffmpeg", "-y",
            "-i", str(video_tmp),
            "-i", str(audio_tmp),
            "-c", "copy",
            "-shortest",
            str(video_path)
        ]
        mr = subprocess.run(merge_cmd, capture_output=True, text=True, timeout=120)
        audio_tmp.unlink(missing_ok=True)
        video_tmp.unlink(missing_ok=True)
        if mr.returncode == 0:
            log(f"  [音频] 修复成功: {video_path.name}")
            return True
        video_tmp.unlink(missing_ok=True)
    log(f"  [音频] 修复失败: {video_path.name}")
    audio_tmp.unlink(missing_ok=True)
    video_tmp.unlink(missing_ok=True)
    return False

def download_youtube_video(video_id: str, output_dir: Path) -> Path | None:
    """下载YouTube视频（优先format18单流保证有音频，备选bestvideo+bestaudio）"""
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / f"{video_id}.mp4"

    if output_file.exists():
        _check_and_fix_audio(output_file)
        log(f"  [下载] 已存在，跳过: {video_id}")
        return output_file

    url = f"https://www.youtube.com/watch?v={video_id}"

    # 策略1: 单流MP4格式（format 18/93/22，无需合并，速度最快）
    # 优先级: 22(720p) > 18(360p) > 93(360p) > best单流
    cmd_single = [
        YTDLP_PY, "-m", "yt_dlp",
        "--cookies-from-browser", "chrome",
        "--extractor-args", "youtube:player_client=web_safari",
        "--no-playlist",
        "-f", "22/18/93/best[ext=mp4]/best",
        "--no-warnings",
        "-o", str(output_file),
        url
    ]

    # 策略2: 系统yt-dlp（更新版本）+ 单流MP4兜底
    cmd_sys = [
        "/opt/homebrew/bin/yt-dlp",
        "--cookies-from-browser", "chrome",
        "--extractor-args", "youtube:player_client=web_safari",
        "--no-playlist",
        "-f", "22/18/93/best[ext=mp4]/best",
        "--no-warnings",
        "-o", str(output_file),
        url
    ]

    # 策略3: hermes venv yt-dlp + 合并格式（最后兜底）
    cmd_merge = [
        YTDLP_PY, "-m", "yt_dlp",
        "--cookies-from-browser", "chrome",
        "--extractor-args", "youtube:player_client=web_safari",
        "--no-playlist",
        "-f", "bestvideo[height<=720]+bestaudio/best",
        "--merge-output-format", "mp4",
        "--no-warnings",
        "-o", str(output_file),
        url
    ]

    strategies = [
        ("单流MP4(hv)", cmd_single),
        ("单流MP4(sys)", cmd_sys),
        ("720p合并", cmd_merge),
    ]

    for attempt in range(3):
        for name, cmd in strategies:
            log(f"  [下载] [{attempt+1}/3] {video_id} ({name})")
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
            if result.returncode == 0 and output_file.exists():
                size_mb = output_file.stat().st_size / 1024 / 1024
                log(f"  [下载] {name}完成 {size_mb:.1f}MB")
                _check_and_fix_audio(output_file)
                return output_file
            log(f"  [下载] {name}失败: {result.stderr[-100:]}")
        if attempt < 2:
            time.sleep(5 * (attempt + 1))

    log(f"  [下载] 最终失败: {video_id}")
    return None
    """
    通过 Playwright 访问 TikTok 搜索页，提取视频数字 ID
    """
    results = []
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        log("  [搜索] playwright 未安装，跳过")
        return results

    async def _search():
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)
            page = await browser.new_page()
            encoded_kw = urllib.parse.quote(keyword)
            search_url = f"https://www.tiktok.com/search?q={encoded_kw}&t=0"
            try:
                await page.goto(search_url, timeout=15000)
                await page.wait_for_timeout(3000)
                # 滚动触发加载
                for _ in range(3):
                    await page.evaluate("window.scrollBy(0, 800)")
                    await asyncio.sleep(1.5)
                content = await page.content()
            finally:
                await browser.close()

            found = re.findall(r'"aweme_id":"(\d{15,})"', content)
            found = list(dict.fromkeys(found))  # 去重保持顺序
            return found[:count]

    try:
        video_ids = asyncio.run(_search())
        for vid in video_ids:
            results.append({
                "id": vid,
                "title": f"AI Story {vid}",
                "keyword": keyword
            })
        if results:
            log(f"  [搜索] Playwright找到 {len(results)} 个视频")
    except Exception as e:
        log(f"  [搜索] Playwright异常: {e}")

    # 备选：用 yt-dlp ytsearch 但只取 TikTok 相关结果
    if not results:
        try:
            search_query = f"ytsearch{count}:tiktok AI {keyword}"
            cmd = [
                YTDLP_PY, "-m", "yt_dlp",
                "--flat-playlist",
                "--print", "%(id)s %(title)s",
                "--no-warnings",
                search_query
            ]
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
            if result.returncode == 0:
                for line in result.stdout.strip().split("\n"):
                    parts = line.split(" ", 1)
                    if len(parts) == 2:
                        vid, title = parts[0].strip(), parts[1].strip()
                        if re.match(r"^[a-zA-Z0-9_-]{10,30}$", vid):
                            results.append({"id": vid, "title": title, "keyword": keyword})
                log(f"  [搜索] yt-dlp fallback 找到 {len(results)} 个")
        except Exception as e:
            log(f"  [搜索] yt-dlp fallback 异常: {e}")

    return results


def search_tiktok_via_api(keyword: str, count: int = 10) -> list[dict]:
    """
    通过TikTok官方搜索页面解析视频数据（无API key方案）
    """
    results = []
    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
    }

    encoded_kw = urllib.parse.quote(keyword)
    url = f"https://www.tiktok.com/search?q={encoded_kw}&t=0"

    try:
        r = _session.get(url, headers=headers, timeout=15)
        if r.status_code != 200:
            log(f"  [TikTok搜索] HTTP {r.status_code}")
            return []

        text = r.text
        # 提取视频ID和标题
        video_ids = re.findall(r'"videoId":"(\d+)"', text)
        titles = re.findall(r'"title":"([^"]{10,200})"', text)
        descs = re.findall(r'"description":"([^"]{10,200})"', text)
        likes = re.findall(r'"diggCount":(\d+)', text)
        views = re.findall(r'"playCount":(\d+)', text)

        for i, vid in enumerate(video_ids[:count]):
            title = titles[i] if i < len(titles) else ""
            desc = descs[i] if i < len(descs) else ""
            like = int(likes[i]) if i < len(likes) else 0
            view = int(views[i]) if i < len(views) else 0

            if not title and not desc:
                title = f"AI Story Video {vid}"
                desc = keyword

            results.append({
                "id": vid,
                "title": title or desc,
                "desc": desc,
                "like": like,
                "view": view,
                "keyword": keyword,
            })
            time.sleep(0.3)
    except Exception as e:
        log(f"  [TikTok搜索] 异常: {e}")

    return results


def get_tiktok_video_info(video_id: str) -> dict:
    """通过TikTok视频页面获取详细元数据"""
    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    }
    url = f"https://www.tiktok.com/video/{video_id}"
    try:
        r = _session.get(url, headers=headers, timeout=15, allow_redirects=True)
        if r.status_code != 200:
            return {}

        text = r.text
        # 提取数据
        like_match = re.search(r'"diggCount":(\d+)', text)
        share_match = re.search(r'"shareCount":(\d+)', text)
        comment_match = re.search(r'"commentCount":(\d+)', text)
        view_match = re.search(r'"playCount":(\d+)', text)
        title_match = re.search(r'"description":"([^"]{1,500})"', text)
        duration_match = re.search(r'"duration":(\d+)', text)

        like = int(like_match.group(1)) if like_match else 0
        share = int(share_match.group(1)) if share_match else 0
        comment = int(comment_match.group(1)) if comment_match else 0
        view = int(view_match.group(1)) if view_match else 0
        title = title_match.group(1) if title_match else f"AI Story {video_id}"
        duration = int(duration_match.group(1)) if duration_match else 0

        return {
            "id": video_id,
            "title": title,
            "like": like,
            "share": share,
            "comment": comment,
            "view": view,
            "duration": duration,
        }
    except Exception as e:
        log(f"  [TikTok详情] {video_id}: {e}")
        return {}


def score_youtube_video(info: dict) -> float:
    """
    YouTube视频评分 — 选中等热度、互动率高的内容
    不要太热（怕被识别），不要太冷（有潜力）
    权重：互动率(50%) + 中等热度(30%) + 时长价值(20%)
    """
    view = max(info.get("view", 0), 1)
    like = info.get("like", 0)
    comment = info.get("comment", 0)
    duration = info.get("duration", 0)

    # 互动率得分 (0-100) — 核心指标，越高越有潜力
    total_engagement = like + comment * 1.5
    engagement_rate = total_engagement / view
    rate_score = min(100, engagement_rate * 20000)

    # 中等热度得分 (0-100) — 不要太热也不要太冷
    # 目标区间：播放100~100万，点赞10~2万（放宽）
    if 500 <= view <= 1000000 and 20 <= like <= 30000:
        heat_score = 100
    elif view < 500:
        heat_score = max(0, 25 - (500 - view) / 20)
    else:
        heat_score = max(25, 80 - (view - 1000000) / 200000)

    # 时长加权 (0-100) — 完播率代理
    if duration > 0:
        if 15 <= duration <= 120:
            duration_score = 100
        elif 5 <= duration < 15:
            duration_score = 60
        elif 120 < duration <= 300:
            duration_score = 80 - (duration - 120) * 0.3
        else:
            duration_score = max(10, 50 - abs(duration - 60) * 0.2)
    else:
        duration_score = 50

    score = (
        rate_score * 0.50 +
        heat_score * 0.30 +
        duration_score * 0.20
    )

    log(f"  评分 [{info['id']}] rate={rate_score:.1f} heat={heat_score:.1f} dur={duration_score:.1f} → {score:.2f} "
        f"(播:{view} 赞:{like} 评:{comment} 时长:{duration}s)")
    return score


# ═══════════════════════════════════════════════════════
# LLM关键词生成
# ═══════════════════════════════════════════════════════
def generate_search_keywords() -> list[str]:
    """用LLM根据当前热点生成AI视频搜索关键词，返回5个不重复的英文关键词"""
    try:
        from llm_utils import call_ollama

        prompt = """You are a TikTok content trends analyst specializing in AI-generated videos.

Current date: 2026-05-30

Generate exactly 5 diverse English search keywords for finding viral AI-generated story/narrative videos on TikTok.

Requirements:
1. Mix of video styles: short films, emotional stories, sci-fi, fantasy, horror, romance, comedy, drama
2. Each keyword must be distinct and NOT overlap with others
3. Use terms like: AI generated, AI story, AI narrative, artificial intelligence, machine story, etc.
4. Focus on content that has high viral potential (emotional, surprising, dramatic)
5. Keywords should be 3-7 words each

Output format (just the keywords, one per line, no numbers or bullets:
[keyword1]
[keyword2]
[keyword3]
[keyword4]
[keyword5]"""

        result = call_ollama(prompt, system="You are a TikTok content analyst. Output only the keywords, one per line, no numbers or bullets.")
        if not result:
            raise ValueError("Empty result")
        text = result.strip()
        import re as re_module
        raw_lines = text.split("\n")
        keywords = []
        for line in raw_lines:
            line = line.strip()
            if not line or len(line) < 4:
                continue
            skip_words = ['i need', 'each ', 'focus on', 'keywords should', 'output format', 'your task', 'generate exactly', 'must be', 'use terms', 'mix of']
            lower_line = line.lower()
            if any(sw in lower_line for sw in skip_words):
                continue
            quoted = re_module.findall(r'"([^"]+)"', line)
            if quoted:
                keywords.extend(quoted)
            else:
                cleaned = re_module.sub(r'^[\-\*\d\.\)\s]+', '', line).strip()
                cleaned = re_module.sub(r'\s*[-–]\s*covers?\s*.*$', '', cleaned).strip()
                if len(cleaned.split()) >= 2 and len(cleaned.split()) <= 7:
                    keywords.append(cleaned)

        seen = set()
        unique_keywords = []
        for k in keywords:
            k_lower = k.lower()
            if k_lower not in seen and len(k) > 3:
                seen.add(k_lower)
                unique_keywords.append(k)

        if len(unique_keywords) >= 3:
            log(f"[LLM] 生成关键词: {unique_keywords[:5]}")
            return unique_keywords[:5]
    except Exception as e:
        log(f"[LLM] 关键词生成失败: {e}")

    return [
        "AI story short film emotional",
        "AI generated narrative drama",
        "artificial intelligence fiction",
        "AI cinematic story viral",
        "machine learning short movie",
    ]

# ═══════════════════════════════════════════════════════
# 字幕生成（faster-whisper）
# ═══════════════════════════════════════════════════════
_SUBTITLE_MODEL = None
_SUBTITLE_LOCK = None

def _get_whisper_model():
    global _SUBTITLE_MODEL, _SUBTITLE_LOCK
    if _SUBTITLE_MODEL is None:
        import threading
        _SUBTITLE_LOCK = threading.Lock()
        with _SUBTITLE_LOCK:
            if _SUBTITLE_MODEL is None:
                from faster_whisper import WhisperModel
                _SUBTITLE_MODEL = WhisperModel("small", device="cpu", compute_type="int8")
    return _SUBTITLE_MODEL

def _extract_audio_for_subtitle(video_path: Path, audio_path: Path) -> bool:
    result = subprocess.run([
        "ffmpeg", "-y", "-i", str(video_path),
        "-vn", "-acodec", "libmp3lame", "-ab", "128k",
        str(audio_path)
    ], capture_output=True, text=True, timeout=120)
    return result.returncode == 0

def _generate_srt_from_audio(audio_path: Path, srt_path: Path) -> bool:
    try:
        model = _get_whisper_model()
        segments, _ = model.transcribe(str(audio_path), language="en", beam_size=5)
        with open(srt_path, "w", encoding="utf-8") as f:
            for i, seg in enumerate(segments):
                start, end, text = seg.start, seg.end, seg.text.strip()
                if not text:
                    continue
                def fmt(t):
                    h, ms = divmod(t, 3600)
                    m, s = divmod(ms, 60)
                    sec, mil = divmod(s, 1)
                    return f"{int(h):02d}:{int(m):02d}:{int(sec):02d},{int(mil*1000):03d}"
                f.write(f"{i+1}\n{fmt(start)} --> {fmt(end)}\n{text}\n\n")
        return True
    except Exception as e:
        log(f"  [字幕] Whisper: {e}")
        return False

def _burn_subtitle(video_path: Path, srt_path: Path, output_path: Path) -> bool:
    """用ffmpeg subtitles滤镜烧录SRT（保留音频，无损流程）"""
    try:
        cmd = [
            "ffmpeg", "-y",
            "-i", str(video_path),
            "-vf", f"subtitles={srt_path}:force_style='FontSize=18,PrimaryColour=&HFFFFFF&,Outline=2,OutlineColour=&H000000&,BorderStyle=3'",
            "-c:v", "libx264", "-preset", "fast", "-crf", "23",
            "-c:a", "aac", "-ar", "44100", "-ac", "2",
            "-movflags", "+faststart",
            str(output_path)
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        if result.returncode != 0:
            log(f"  [字幕] ffmpeg烧录失败: {result.stderr[-300:]}")
            return False
        return output_path.exists()
    except Exception as e:
        log(f"  [字幕] 异常: {e}")
        return False

def burn_subtitle(video_file: Path, vid: str) -> Path | None:
    """提取音频→Whisper生成SRT→烧录字幕→合并音频→返回新视频路径"""
    audio_path = WORK_DIR / f"{vid}_audio.mp3"
    srt_path   = WORK_DIR / f"{vid}.srt"
    subbed     = WORK_DIR / f"{vid}_subbed.mp4"

    # 如果已有烧录好的视频，直接返回
    if subbed.exists():
        log("[字幕] 已有烧录版本，跳过")
        return subbed

    log("[字幕] 提取音频...")
    if not _extract_audio_for_subtitle(video_file, audio_path):
        log("[字幕] 音频提取失败，保留原文件")
        return video_file

    log("[字幕] 生成SRT (Whisper EN)...")
    if not _generate_srt_from_audio(audio_path, srt_path):
        audio_path.unlink(missing_ok=True)
        log("[字幕] SRT失败")
        return video_file

    # 检查SRT是否有效（字幕块太少则跳过）
    with open(srt_path, "r", encoding="utf-8") as f:
        srt_content = f.read()
    srt_lines = srt_content.strip().split("\n")
    subtitle_blocks = [i for i, l in enumerate(srt_lines) if l.strip().isdigit()]
    if len(subtitle_blocks) < 3:
        log(f"[字幕] 字幕块太少({len(subtitle_blocks)}个)，跳过烧录")
        audio_path.unlink(missing_ok=True)
        srt_path.unlink(missing_ok=True)
        return video_file

    log("[字幕] 烧录...")
    if not _burn_subtitle(video_file, srt_path, subbed):
        audio_path.unlink(missing_ok=True)
        srt_path.unlink(missing_ok=True)
        log("[字幕] 烧录失败")
        return video_file

    # ffmpeg subtitles直接保留原音频，无需额外合并
    log("[字幕] 清理临时文件...")
    audio_path.unlink(missing_ok=True)
    srt_path.unlink(missing_ok=True)
    log("[字幕] 完成（含原始音频）")
    return subbed



def crop_video(input_file: Path, output_file: Path) -> Path | None:
    """上下左右各裁剪1%，用于去重处理"""
    try:
        probe = subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "v:0",
             "-show_entries", "stream=width,height", "-of", "json", str(input_file)],
            capture_output=True, text=True, timeout=30
        )
        info = json.loads(probe.stdout)
        streams = info.get("streams", [])
        if not streams:
            log("  [裁剪] 无法获取视频尺寸")
            return None
        w = streams[0]["width"]
        h = streams[0]["height"]
    except Exception as e:
        log(f"  [裁剪] ffprobe失败: {e}")
        return None

    crop_pct = 0.01
    new_w = int(w * (1 - crop_pct * 2))
    new_h = int(h * (1 - crop_pct * 2))
    x_offset = int(w * crop_pct)
    y_offset = int(h * crop_pct)

    crop_filter = f"crop={new_w}:{new_h}:{x_offset}:{y_offset}"
    cmd = [
        "ffmpeg", "-y", "-i", str(input_file),
        "-vf", crop_filter,
        "-c:v", "libx264", "-preset", "fast", "-crf", "23",
        "-c:a", "aac", "-ar", "44100", "-ac", "2",
        "-movflags", "+faststart",
        str(output_file)
    ]
    log(f"  [裁剪] {w}x{h} -> {new_w}x{new_h}")

    for attempt in range(3):
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        if result.returncode == 0 and output_file.exists():
            size_mb = output_file.stat().st_size / 1024 / 1024
            log(f"  [裁剪] 完成 ({size_mb:.1f}MB)")
            return output_file
        log(f"  [裁剪] 失败 (attempt {attempt+1}): {result.stderr[-200:]}")
        if attempt < 2:
            time.sleep(3 * (attempt + 1))

    return None


# ═══════════════════════════════════════════════════════
# 下载
# ═══════════════════════════════════════════════════════
def download_tiktok_video(video_id: str, output_dir: Path) -> Path | None:
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / f"{video_id}.mp4"

    if output_file.exists():
        log(f"  [下载] 已存在，跳过: {video_id}")
        return output_file

    url = f"https://www.tiktok.com/@/video/{video_id}"
    cmd = [
        YTDLP_PY, "-m", "yt_dlp",
        "--no-playlist",
        "--cookies", str(TIKTOK_COOKIE_FILE),
        "-f", "bestvideo[height<=1080]+bestaudio/best[height<=1080]/best",
        "--merge-output-format", "mp4",
        "--no-warnings",
        "-o", str(output_file),
        url
    ]

    for attempt in range(3):
        log(f"  [下载] [{attempt+1}/3] {video_id}")
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        if result.returncode == 0 and output_file.exists():
            size_mb = output_file.stat().st_size / 1024 / 1024
            log(f"  [下载] 完成 {output_file} ({size_mb:.1f}MB)")
            return output_file
        log(f"  [下载] 失败 (attempt {attempt+1}): {result.stderr[-200:]}")
        if attempt < 2:
            time.sleep(5 * (attempt + 1))

    log(f"  [下载] 最终失败: {video_id}")
    return None


# ═══════════════════════════════════════════════════════
# B站上传
# ═══════════════════════════════════════════════════════
def generate_cover(video_file: Path, vid: str, title: str) -> Path:
    """从视频提取关键帧作为封面，加标题文字"""
    cover_path = WORK_DIR / f"{vid}_cover.png"
    if cover_path.exists():
        return cover_path

    thumb = WORK_DIR / f"{vid}_thumb.jpg"

    # 1. 尝试提取视频第一帧
    try:
        r = subprocess.run([
            "ffmpeg", "-y", "-i", str(video_file),
            "-vf", "select=eq(n\,0),scale=1280:720",
            "-frames:v", "1", "-q:v", "2",
            str(thumb)
        ], capture_output=True, text=True, timeout=60)
        if r.returncode != 0 or not thumb.exists():
            raise ValueError("ffmpeg frame grab failed")
    except Exception:
        # fallback：纯色封面
        from PIL import Image, ImageDraw, ImageFont
        img = Image.new('RGB', (1280, 720), color=(20, 25, 60))
        draw = ImageDraw.Draw(img)
        words = "AI Story"
        try:
            font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 60)
        except Exception:
            font = ImageFont.load_default()
        bbox = font.getbbox(words)
        bw, bh = bbox[2] - bbox[0], bbox[3] - bbox[1]
        draw.text(((1280-bw)//2, (720-bh)//2), words, fill=(200, 200, 255), font=font)
        img.save(cover_path)
        return cover_path

    # 2. PIL处理：缩放+加文字遮罩
    try:
        from PIL import Image as PILImage, ImageDraw, ImageFont
        img = PILImage.open(thumb).convert("RGB")
        img = img.resize((1280, 720), PILImage.LANCZOS)
        draw = ImageDraw.Draw(img)
        # 半透明黑色底部遮罩
        overlay = PILImage.new('RGB', (1280, 720), (0, 0, 0))
        mask = PILImage.new('L', (1280, 720), 0)
        mask_draw = ImageDraw.Draw(mask)
        mask_draw.rectangle([(0, 560), (1280, 720)], fill=180)
        overlay.paste(img, (0, 0))
        img = PILImage.composite(overlay, PILImage.new('RGB', (1280, 720), (0, 0, 0)), mask)
        draw = ImageDraw.Draw(img)
        short_title = title[:30] + ("…" if len(title) > 30 else "")
        try:
            font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 48)
        except Exception:
            font = ImageFont.load_default()
        draw.text((40, 570), short_title, fill=(255, 255, 255), font=font)
        draw.text((40, 640), "AI故事视频", fill=(180, 180, 255), font=font)
        img.save(cover_path, quality=92)
        thumb.unlink(missing_ok=True)
    except Exception as e:
        log(f"  [封面] PIL处理失败: {e}")
        if thumb.exists() and not cover_path.exists():
            thumb.rename(cover_path)

    return cover_path


# ═══════════════════════════════════════════════════════
# B站上传
# ═══════════════════════════════════════════════════════
def biliup_upload(video_path: str, title: str, desc: str, tid: int = 21) -> str | None:
    """上传视频到B站，返回bvid或None"""
    video_path = Path(video_path)
    if not video_path.exists():
        log(f"  [B站上传] 文件不存在: {video_path}")
        return None

    try:
        import asyncio
        from bilibili_api import Credential
        from bilibili_api.video_uploader import VideoUploader, VideoUploaderPage, VideoMeta, Lines
        from bilibili_api.utils.picture import Picture

        vid = video_path.stem.replace("_subbed", "").replace("_cropped", "")
        cover_path = generate_cover(video_path, vid, title)

        cookies = load_cookies(BILI_COOKIE_FILE)
        cred = Credential(
            sessdata=cookies.get('SESSDATA', ''),
            bili_jct=cookies.get('bili_jct', ''),
            buvid3=cookies.get('buvid3', '')
        )

        async def do_upload():
            import warnings
            warnings.filterwarnings('ignore')
            meta = VideoMeta(
                tid=tid,
                title=title,
                desc=desc,
                cover=Picture.from_file(str(cover_path)),
                tags=["AI故事", "TikTok搬运", "故事生成", "AI创作"],
                source="https://www.tiktok.com",
            )
            page = VideoUploaderPage(
                path=str(video_path),
                title=title,
                description=desc
            )
            uploader = VideoUploader(pages=[page], meta=meta, credential=cred, line=Lines.BDA2)
            ret = await uploader.start()
            return ret

        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        result = loop.run_until_complete(do_upload())
        loop.close()

        if isinstance(result, dict) and result.get("bvid"):
            log(f"  [B站上传] 成功: {result['bvid']}")
            return result["bvid"]
        log(f"  [B站上传] 完成，无bvid返回")
        return result if result else True
    except Exception as e:
        log(f"  [B站上传] 失败: {e}")
        return None


# ═══════════════════════════════════════════════════════
# 抖音上传
# ═══════════════════════════════════════════════════════
def douyin_upload(video_path: str, title: str, desc: str) -> bool:
    """通过复用ai_video_upload/douyin_upload.py上传到抖音"""
    try:
        import asyncio
        sys.path.insert(0, str(DOUYIN_UPLOAD_SCRIPT.parent))
        from douyin_upload import upload_to_douyin

        result = asyncio.get_event_loop().run_until_complete(
            upload_to_douyin(video_path, title, desc)
        )
        if result:
            log(f"  [抖音上传] 成功")
            return True
        log(f"  [抖音上传] 返回失败")
        return False
    except Exception as e:
        log(f"  [抖音上传] 异常: {e}")
        return False


def douyin_upload_sync(video_path: str, title: str, desc: str) -> bool:
    """同步版本的抖音上传（启动独立进程执行douyin_upload.py）"""
    try:
        cmd = [
            YTDLP_PY, str(DOUYIN_UPLOAD_SCRIPT),
            "--video", video_path,
            "--title", title,
            "--desc", desc,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        if result.returncode == 0:
            log(f"  [抖音上传] 成功")
            return True
        log(f"  [抖音上传] 失败: {result.stderr[-200:]}")
        return False
    except Exception as e:
        log(f"  [抖音上传] 异常: {e}")
        return False


# ═══════════════════════════════════════════════════════
# LLM生成简介
# ═══════════════════════════════════════════════════════
def generate_desc_and_title(title: str, keyword: str) -> tuple[str, str]:
    """用LLM根据标题生成B站标题和简介"""
    try:
        import urllib.request

        payload = {
            "model": "qwen2.5:32b-instruct",
            "messages": [{
                "role": "user",
                "content": f'''根据这个TikTok视频的标题，生成B站风格的标题和简介。

原标题: {title}
搜索关键词: {keyword}

要求：
1. B站标题：吸引眼球，可以有emoji，15-40字，包含AI、故事等关键词
2. 简介：2-3句，概括视频精彩内容，引导点赞投币关注，带2-3个相关标签

格式：
标题：[标题]
简介：[简介]'''
            }],
            "stream": False,
            "max_tokens": 150,
            "temperature": 0.7
        }

        req = urllib.request.Request(
            "http://localhost:11434/v1/chat/completions",
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=60) as resp:
            result = json.loads(resp.read().decode("utf-8"))

        text = result["choices"][0]["message"]["content"].strip()
        log(f"  [LLM] 原始输出:\n{text[:300]}")

        new_title = title
        desc = f"AI故事 · {datetime.now().strftime('%Y-%m-%d')}"

        for line in text.split("\n"):
            line = line.strip()
            if line.startswith("标题："):
                new_title = line[3:].strip()
            elif line.startswith("简介："):
                desc = line[3:].strip()

        if len(new_title) > 50:
            new_title = title[:45] + "..."

        return new_title, desc
    except Exception as e:
        log(f"  [LLM] 生成失败: {e}")
        return title, f"AI故事视频 · {datetime.now().strftime('%Y-%m-%d')}"


# ═══════════════════════════════════════════════════════
# 流水线主逻辑
# ═══════════════════════════════════════════════════════
def run_pipeline():
    open(LOG_FILE, "w").close()

    log("=" * 60)
    log("YouTube故事AI视频搬运流水线启动")

    if not acquire_lock():
        log("另一个进程正在运行，退出")
        return

    WORK_DIR.mkdir(parents=True, exist_ok=True)

    # 0. 网络预检
    try:
        import urllib.request
        req = urllib.request.Request(NETWORK_TEST_URL, headers={"User-Agent": "curl/8.0"})
        with urllib.request.urlopen(req, timeout=NETWORK_TEST_TIMEOUT) as resp:
            if resp.status == 200:
                log(f"[网络] YouTube可访问 ✅")
            else:
                log(f"[网络] YouTube返回{resp.status}，继续...")
    except Exception as e:
        log(f"[网络] YouTube预检失败: {e}，继续...")

    # 1. LLM生成搜索关键词（不够时自动扩容）
    keywords = generate_search_keywords()
    while len(keywords) < 8:
        keywords.append(random.choice([
            "AI generated emotional short film",
            "artificial intelligence story drama",
            "AI cinematic viral short",
            "machine story sci-fi adventure",
            "AI horror mystery short film",
            "AI romance drama short video",
            "AI narrative fantasy realm",
            "surprising AI generated story",
        ]))
        log(f"[关键词] LLM关键词不足，自动补足: {keywords[-1]}")
    log(f"[关键词] 共{len(keywords)}个: {keywords[:5]}...")

    # 2. 搜索YouTube
    all_results = []
    for kw in keywords:
        log(f"[搜索] YouTube关键词: {kw}")
        results = search_youtube(kw, count=SEARCH_COUNT_PER_KEYWORD)
        log(f"  找到 {len(results)} 个视频")
        all_results.extend(results)
        time.sleep(2)

    log(f"[搜索] 共找到 {len(all_results)} 个视频")
    if not all_results:
        log("[搜索] 失败，退出")
        return

    # 3. 排除历史
    history = load_history()
    upload_history = load_upload_history()
    downloaded = set(history.keys())
    uploaded = set(upload_history.keys())
    candidates = [v for v in all_results if v["id"] not in downloaded and v["id"] not in uploaded]
    log(f"[候选] {len(candidates)}个（已排除下载过{len(all_results)-len(candidates)-len(uploaded)}个 + 已上传{len(uploaded)}个）")

    if not candidates:
        log("[候选] 没有新视频，退出")
        return

    # 4. 获取详细信息并打分（并行，8线程）
    scored = []
    def get_info_with_score(v):
        info = get_youtube_video_info(v["id"])
        if not info or not info.get("title"):
            info = v  # fallback
        info["keyword"] = v.get("keyword", "")
        info["duration"] = v.get("duration", info.get("duration", 0))
        score = score_youtube_video(info)
        info["score"] = score
        return info

    with ThreadPoolExecutor(max_workers=8) as executor:
        futures = {executor.submit(get_info_with_score, v): v for v in candidates[:TOP_CANDIDATES]}
        for future in as_completed(futures):
            info = future.result()
            vid = info["id"]
            log(f"  [{vid}] 赞:{info.get('like',0)} 播:{info.get('view',0)} 时长:{info.get('duration',0)}s → 评分:{info['score']:.4f}")
            scored.append(info)

    # 过滤超长视频
    before_filter = len(scored)
    scored = [v for v in scored if v.get("duration", 0) <= MAX_VIDEO_DURATION]
    log(f"[时长过滤] {before_filter} -> {len(scored)} 个（排除>{MAX_VIDEO_DURATION}秒的）")

    if not scored:
        log("[评分] 无可用视频，退出")
        return

    scored.sort(key=lambda x: x["score"], reverse=True)
    top_videos = scored[:MAX_DOWNLOADS_PER_RUN]

    log(f"[选中] 将处理 {len(top_videos)} 个视频")

    for video in top_videos:
        vid = video["id"]
        title = video.get("title", f"YouTube {vid}")
        keyword = video.get("keyword", "")
        log(f"\n{'='*40}")
        log(f"[处理] {vid}: {title}")

        # 5. 下载YouTube视频
        log("[下载] 开始下载...")
        video_file = download_youtube_video(vid, WORK_DIR)
        if not video_file:
            log("[下载] 失败，跳过")
            continue

        size_mb = video_file.stat().st_size / 1024 / 1024
        if size_mb < 0.5:
            log(f"[下载] 文件太小({size_mb:.1f}MB)，跳过")
            continue

        # 6. 裁剪视频（上下左右各裁剪1%）
        log("[裁剪] 开始裁剪1%...")
        cropped_file = WORK_DIR / f"{vid}_cropped.mp4"
        crop_result = crop_video(video_file, cropped_file)
        if crop_result:
            video_file.unlink()
            video_file = cropped_file
            log("[裁剪] 完成")
        else:
            log("[裁剪] 失败，使用原文件")

        # 6b. 生成并烧录字幕（Whisper英文转SRT烧录ASS）
        log("[字幕] 生成中文字幕...")
        video_file = burn_subtitle(video_file, vid)

        # 7. 生成标题描述
        log("[LLM] 生成标题和简介...")
        new_title, desc = generate_desc_and_title(title, keyword)
        log(f"  标题: {new_title}")
        log(f"  简介: {desc[:50]}...")

        # 8. B站上传
        log("[B站] 开始上传...")
        bili_result = biliup_upload(str(video_file), new_title, desc)
        if bili_result:
            log("✅ B站上传成功!")
        else:
            log("⚠️ B站上传失败")

        # 8b. 抖音上传
        log("[抖音] 开始上传...")
        douyin_result = douyin_upload_sync(str(video_file), new_title, desc)
        if douyin_result:
            log("✅ 抖音上传成功!")
        else:
            log("⚠️ 抖音上传失败")

        # 9. 记录历史
        history[vid] = {
            "title": title,
            "new_title": new_title,
            "downloaded_at": time.strftime("%Y-%m-%d %H:%M"),
            "file": str(video_file),
            "bili_result": str(bili_result),
            "douyin_result": str(douyin_result),
        }
        save_history(history)

        if bili_result:
            upload_history[vid] = {
                "title": new_title,
                "uploaded_at": time.strftime("%Y-%m-%d %H:%M"),
            }
            save_upload_history(upload_history)

        log(f"[完成] {vid} 处理完毕")

    log("=" * 60)
    log("✅ 流水线完成!")


if __name__ == "__main__":
    run_pipeline()